### ISSUE TITLE
Promises missing?

### ISSUE THREAD

**Issue by angelxmoreno** [dial-once/node-cache-manager-redis#31]
Not sure if I am doing something wrong in my setup, but when I try to use promises in multicache, I don't ever get the cache data. 

Is this adapter not compatible with promises?

**Comment by mrister** [comment]
@angelxmoreno  Any chance you can provide example code to test? Promises should be supported.

**Comment by mrister** [comment]
@angelxmoreno This lib is not yet promise ready.

**Comment by PuKoren** [comment]
As a side note, because I'm not sure to understand what is your issue:

When you use directly node-cache-manager-redis, you can't use the exposed methods as promises (`.get`, `.set`, `.ttl`, etc.).

However if you are using node-cache-manager, and the multicache feature (since you mentioned it), promises should be handled for you since version 1.3 of node-cache-manager: https://github.com/BryanDonovan/node-cache-manager/releases/tag/1.3.0

And you can do `.wrap`, `.get`, etc. on the `multicache` object and expect a promise as return value of those methods.

To fully understand your issue, can you provide your node-cache-manager version, as well as a sample code that is failing?

**Comment by angelxmoreno** [comment]
ty. will test soon

**Comment by jeff-kilbride** [comment]
For anyone looking to use promises, I have found using `bluebird` to be the easiest solution. Here is an example:
```js
const cacheManager = require('cache-manager'),
      redisStore   = require('cache-manager-redis'),
      Promise      = require('bluebird');

const cache = cacheManager.caching({
    store: redisStore,
    host: config.host,
    port: config.port,
    ttl: config.ttl,
    promiseDependency: Promise
});

Promise.promisifyAll(cache);

cache.store.getClientAsync = Promise.promisify(cache.store.getClient, { context: cache.store });
```
This creates async versions of all the available methods with an `Async` suffix.
```js
cache.setAsync('foo', 'bar').then(function(result) { });
```
etc...  Or, even better, if you are using generators:
```js
let value = yield cache.getAsync('foo');
```
You can even promisify individual methods of the underlying redis client with something like this:
```js
cache.store.getClient(function (err, redis) {
    redis.client.mgetAsync = Promise.promisify(redis.client.mget, { context: redis.client });
    redis.client.msetAsync = Promise.promisify(redis.client.mset, { context: redis.client });
    redis.done();
});
```
Although the update to `sol-redis-pool` 3.x is causing some errors with this, now. I am currently trying to get the author of that package to add `bluebird` support, so all clients in the underlying pool are promisified automatically. (If you would also like to see this, you can add your comments / support to [the issue I created here](https://github.com/joshuah/sol-redis-pool/issues/21).)

**Comment by angelxmoreno** [comment]
closing in favor of @jeff-kilbride snippet
