### ISSUE TITLE
Why is a connection pool used?

### ISSUE THREAD

**Issue by kjs3** [dial-once/node-cache-manager-redis#76]
I'm just curious why `sol-redis-pool` is used vs `node_redis` directly?

[This issue](https://github.com/NodeRedis/node_redis/issues/226) suggests that we lose pipelining optimizations. Was performance an issue without a pool?

**Comment by mrister** [comment]
I'm not exactly sure, I guess it was due to connection reuse. It is an interesting question though.  After reading:
-  https://redis.io/topics/pipelining, 
- https://github.com/NodeRedis/node_redis/issues/539#issuecomment-32203325,

I am not sure pipelining in node_redis is avail using commands done in this lib but only multi and batch ones. However this requires some research and comparison, @kjs3 did you have a specific use case in mind ?

**Comment by jeff-kilbride** [comment]
Honestly, I don't think the connection pool is necessary and it adds a bit of complexity, having to retrieve and release each connection. Getting rid of the pool may also help with issues like #66 and #70.

**Comment by mrister** [comment]
I think #66 is related to usage of JSON.stringify and not so much the pool, you are right on other points though.

**Comment by yktv4** [comment]
Hey guys. I was wondering what if there was a configuration option to pass a `redis` client from outside? Ideally the syntax could be something like this:

```js
const cacheManager = require('cache-manager');
const RedisStore = require('cache-manager-redis');
const redis = require('redis');
const redisClient = redis.createClient();

const store = new RedisStore({ redisClient });
const cacheManager = cacheManager.caching({ store });
```

Although I'm not sure this syntax is possible due to possible backwards compatibility issues. This would add the ability for external control over the redis connection without the hassle to code some getter function inside of `node-cache-manager-redis`.

**Comment by mrister** [comment]
@kjs3 since we use sol-redis-pool, you can pass Redis options like this https://github.com/lzyzsd/sol-redis-pool#additional-redis-options which are basically options for the client like mentioned here https://github.com/NodeRedis/node_redis#options-object-properties
would this help?
